# Generated by Django 5.1.1 on 2024-10-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=255)),
                ('train_number', models.CharField(max_length=7)),
                ('from_station', models.CharField(max_length=255)),
                ('to_station', models.CharField(max_length=255)),
                ('departure_time', models.CharField(max_length=255)),
                ('arrival_time', models.CharField(max_length=255)),
                ('available_seats', models.CharField(max_length=255)),
            ],
        ),
    ]
