# Generated by Django 5.1.1 on 2024-10-22 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_train'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('pnr_number', models.AutoField(primary_key=True, serialize=False)),
                ('people_count', models.IntegerField()),
                ('date', models.CharField(max_length=255)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railway.train')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railway.user')),
            ],
        ),
    ]
